-- Student Groups feature (Feature 1)
-- Applied manually to live DB (matching established raw-SQL pattern).

CREATE TABLE IF NOT EXISTS "StudentGroups" (
    "Id"          uuid NOT NULL,
    "TeacherId"   uuid NOT NULL,
    "Name"        character varying(200) NOT NULL,
    "Description" character varying(500) NULL,
    "SubjectId"   uuid NULL,
    "Color"       text NOT NULL DEFAULT '#6366f1',
    "CreatedAt"   timestamp with time zone NOT NULL,
    "UpdatedAt"   timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StudentGroups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentGroups_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Users"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StudentGroups_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects"("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_StudentGroups_TeacherId" ON "StudentGroups" ("TeacherId");
CREATE INDEX IF NOT EXISTS "IX_StudentGroups_SubjectId" ON "StudentGroups" ("SubjectId");

CREATE TABLE IF NOT EXISTS "StudentGroupMembers" (
    "Id"             integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StudentGroupId" uuid NOT NULL,
    "StudentId"      uuid NOT NULL,
    "JoinedAt"       timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StudentGroupMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentGroupMembers_StudentGroups_StudentGroupId" FOREIGN KEY ("StudentGroupId") REFERENCES "StudentGroups"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StudentGroupMembers_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users"("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_StudentGroupMembers_StudentGroupId" ON "StudentGroupMembers" ("StudentGroupId");
CREATE INDEX IF NOT EXISTS "IX_StudentGroupMembers_StudentId" ON "StudentGroupMembers" ("StudentId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_StudentGroupMembers_StudentGroupId_StudentId" ON "StudentGroupMembers" ("StudentGroupId", "StudentId");